export default function Head() {
  return (
    <>
      <title>Frontend Mentor - Article preview component solution</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />

      {/* <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
      <link href="https://fonts.googleapis.com/css2?family=Manrope:wght@500;700&display=swap" rel="stylesheet" precedence="default" /> */}

      <link rel="icon" href="/favicon.ico" />
    </>
  )
}
